language: "node_js"
env:
  - CXX=g++-4.8
addons:
  rethinkdb: '2.3.5'
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
  - "11"
after_script:
  - npm run reports:coveralls
